"""First Revison

Revision ID: 01efd6e6068c
Revises: 
Create Date: 2023-05-20 10:38:31.571008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01efd6e6068c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
